version: '3.8'

services:
  web:
    build: .
    ports:
      - "8090:443"
      - "2001:2001"
    volumes:
      - ./public/files:/var/www/html/public/files
      - ./public/resources:/var/www/html/public/resources
      - ./ssl:/etc/apache2/ssl
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - HTTPS=on
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cauldron
      MYSQL_USER: cauldron
      MYSQL_PASSWORD: cauldron
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: